### PR TITLE
Add path paramter, default value is set to False.

### PR DESCRIPTION
**Pull request by yfxia**

### CODE REVIEW

**Comment by yfxia** [comment]
@VictorKong94 This is a slight modification in .init method, just to make my script run. The default value is set to False. Please let me know if you feel comfortable with it. Since the path to make coverage and run script are different, this is one possible solution that I can think of. Thanks a lot.

**Comment by VictorKong94** [comment]
Which scripts require this modification?

**Comment by yfxia** [comment]
right now run_logistic_model, but actually every script needs this modification, since make_class is not in the directory as the 'data' folder.

**Comment by liuanna** [comment]
Since make_class.py is in utils while data is in main directory, every time we try to create a run object, it raises an error because make_class cannot access ```data/ds005/sub%s/" % sub_id``` at current directory.

**Pull request closed without merging**
