### PR TITLE
Proposed new convolution script and test

### PR DESCRIPTION
**Pull request by VictorKong94**

### CODE REVIEW

**Comment by VictorKong94** [comment]
Going to figure this out. Please don't merge yet.

**Comment by liuanna** [comment]
I have some ideas. Maybe we can use use the simplest way to wrap up all 16 subjects and runs. We can just rewrite all scripts and add a for loop to let script run over all subjects. Then we can save time from writing test files and fixing coverage.

**Comment by liuanna** [comment]
By the way, would you mind creating a new folder called "final" or something else which contains all the stuff that you write for the final result? Since other scripts I am writing are based on run_conv_scripts.py, please keep it for a while. We can delete them at the end. Thank you.

**Comment by VictorKong94** [comment]
I thought it might be a good idea to test the code just to make sure it works before doing it 48 times anyway. How do you propose we write the `for` loop you have in mind? Where should this `final` folder be?

**Comment by liuanna** [comment]
I mean we don't have to write functions for scripts. Since we have almost done the scripts for one subjects, that means the scripts work for one subject. 
For each type of analysis, we can do something like this:

 ```
import os
    sub_id = ["001","002","003","004","005","006","007","008","009","010","011","012","013","014","015","016"]
    run_id = ["001","002","003"]
    pair_id = list(zip([i for _ in range(3) for i in sub_id], [i for i in run_id for _ in range(16)]))

    path = "results"
    if not os.path.exists(path):
        os.makedirs(path)
        for i in sub_id:
            os.makedirs(path+"/sub"+i)
            for j in run_id:
                os.makedirs(path+"/sub"+i+"/run"+j)
for p in pair_id:
    # for example:
    s, r = p
   # saving path
   save_path = "results/sub%s/run%s/" % (s, r)
   sub = ds005(r,s)
   neural_gain = sub.filtered.time_course("gain", step_size=0.02) # where 0.02 = TR/tr_divs
   neural_loss = sub.filtered.time_course("loss", step_size=0.02)
   neural_dist = sub.filtered.time_course("dist2indiff", step_size=0.02)
   ..................( content of scripts, i.e. logistic, linear, etc)
```

You can place the final folder in the main directory or anywhere you feel appropriate.

**Comment by liuanna** [comment]
Are you available tomorrow after 5pm? We'd better have a meeting and finish these codes ASAP.

**Comment by VictorKong94** [comment]
I can meet tomorrow. And I think I'm actually going to merge your PR instead, but I'm going to change some things in your `Makefile` and `run_conv_script.py`.
Questions: Does it NEED to be named `run_conv_script.py`? Do each of the runs NEED to be a separate directory, or can you work with a directory called `results` that has a subdirectory for each run? Where do you want to download the "make color" file to?

**Comment by liuanna** [comment]
You can change the filename. The only thing that you'd better preserve is the output files. I feel it will be more organized if we put the result for each run into a separate directory. Since I am plotting parameter map in linear_analysis_script, I need actc.txt. Right now, it is downloaded in main directory. If you find a more appropriate location for it, just move it and let me know. 
The reason I change zero to nan is that nan will just show no color while zero will actually show color.

**Pull request closed without merging**
